language: android

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-25.0.1
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - sys-img-x86-android-25
    - sys-img-armeabi-v7a-android-17



jdk:
  - oraclejdk8

sudo: required

before_install:
 - chmod +x gradlew
 - echo no | Android/Sdk/tools/bin/avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-23;google_apis;x86_64'
 - yes | sdkmanager "platforms;android-28" 
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &
